"""test

Revision ID: 27781c60e136
Revises: e6b02c4571f0
Create Date: 2026-04-16 23:38:09.117037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27781c60e136'
down_revision: Union[str, Sequence[str], None] = 'e6b02c4571f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('published', 'archived', 'unlisted', 'draft', name='articlestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('article_tags',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='role'),
               type_=sa.Enum('user', 'admin', name='role', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', name='role', native_enum=False),
               type_=postgresql.ENUM('USER', 'ADMIN', name='role'),
               existing_nullable=False)
    op.drop_table('article_tags')
    op.drop_table('articles')
    op.drop_table('tags')
    # ### end Alembic commands ###
